---
config:
  layout: elk
  elk:
    mergeEdges: false
  class:
    hideEmptyMembersBox: true
---

classDiagram
    direction LR

    class Company
    class User
    class RefreshToken
    class License
    class Policy
    class Device
    class EnrollmentToken
    class SecurityEvent
    class UrlRule
    class DownloadRule

    Company "1" -- "1..*" User : agrupa
    Company "1" -- "0..*" License : contiene
    Company "1" -- "0..*" Policy : define
    Company "1" -- "0..*" Device : registra

    User "1" -- "0..*" Device : tiene instalaciones
    User "1" -- "0..*" RefreshToken : mantiene tokens
    License "1" -- "0..*" Device : cubre
    Policy "1" -- "0..*" Device : se asigna a

    User "1" -- "0..*" EnrollmentToken : recibe
    License "1" -- "0..*" EnrollmentToken : autoriza

    Policy "1" -- "0..*" EnrollmentToken : fija politica inicial
    EnrollmentToken "1" -- "0..1" Device : registra instalacion

    Device "1" -- "0..*" SecurityEvent : genera

    Policy "1" -- "0..*" UrlRule : incluye dominios
    Policy "1" -- "0..*" DownloadRule : incluye extensiones

    note for Company "Debe conservar al menos un User con rol ADMIN"