---
config:
  class:
    hideEmptyMembersBox: true
---

classDiagram
    direction LR

    class Company
    class User
    class License
    class Policy
    class Device
    class EnrollmentToken
    class SecurityEvent

    Company "1" -- "1..*" User : agrupa
    Company -- License : contiene
    Company -- Policy : define
    Company -- Device : registra

    User -- Device : tiene instalaciones
    License -- Device : cubre
    Policy -- Device : se asigna a

    User -- EnrollmentToken : recibe
    License -- EnrollmentToken : autoriza

    Device "1" -- "0..*" SecurityEvent : genera

    note for Company "Debe conservar al menos un User con rol ADMIN"